// Copyright 2016 Yahoo Inc.
// Licensed under the terms of the New-BSD license. Please see LICENSE file in the project root for terms.
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_jni_example_ExampleJniAccess */

#ifndef _Included_com_yahoo_jni_example_ExampleJniAccess
#define _Included_com_yahoo_jni_example_ExampleJniAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_jni_example_ExampleJniAccess
 * Method:    executeCWithCallBack
 * Signature: (Lcom/yahoo/jni/example/CallbackInterface;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_jni_example_ExampleJniAccess_executeCWithCallBack
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
