/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_jni_example_ExampleJniAccess */

#ifndef _Included_com_yahoo_jni_example_ExampleJniAccess
#define _Included_com_yahoo_jni_example_ExampleJniAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_jni_example_ExampleJniAccess
 * Method:    executeCWithCallBackInSameThread
 * Signature: (Lcom/yahoo/jni/example/CallbackInterface;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_jni_example_ExampleJniAccess_executeCWithCallBackInSameThread
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_jni_example_ExampleJniAccess
 * Method:    executeCWithCallBackInNewThread
 * Signature: (Lcom/yahoo/jni/example/CallbackInterface;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_jni_example_ExampleJniAccess_executeCWithCallBackInNewThread
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_jni_example_ExampleJniAccess
 * Method:    executeCWithCallBackInSharedThread
 * Signature: (Lcom/yahoo/jni/example/CallbackInterface;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_jni_example_ExampleJniAccess_executeCWithCallBackInSharedThread
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
